package it.polimi.ingsw.model.board.goalCards;

import it.polimi.ingsw.Launcher;
import it.polimi.ingsw.model.board.ItemTile;
import it.polimi.ingsw.model.player.BookShelf;
import junit.framework.TestCase;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class CommonGoalCard3Test extends TestCase {

    public void testCheckGoalCardCGC3_FIRST() {
        CommonGoalCard c44 = new CommonGoalCard3(new Launcher());
        c44.initNumCompleted();
        BookShelf bs30 = new BookShelf();
        bs30.setTile(0, 0, new ItemTile("BOOKS"));
        bs30.setTile(1, 0, new ItemTile("BOOKS"));
        bs30.setTile(2, 0, new ItemTile("BOOKS"));
        bs30.setTile(3, 0, new ItemTile("BOOKS"));
        bs30.setTile(4, 0, new ItemTile("GAMES"));
        bs30.setTile(5, 0, new ItemTile("CATS"));
        bs30.setTile(0, 1, new ItemTile("FRAMES"));
        bs30.setTile(1, 1, new ItemTile("GAMES"));
        bs30.setTile(2, 1, new ItemTile("FRAMES"));
        bs30.setTile(3, 1, new ItemTile("FRAMES"));
        bs30.setTile(4, 1, new ItemTile("GAMES"));
        bs30.setTile(5, 1, new ItemTile("CATS"));
        bs30.setTile(0, 2, new ItemTile("PLANTS"));
        bs30.setTile(1, 2, new ItemTile("PLANTS"));
        bs30.setTile(2, 2, new ItemTile("FRAMES"));
        bs30.setTile(3, 2, new ItemTile("CATS"));
        bs30.setTile(4, 2, new ItemTile("TROPHIES"));
        bs30.setTile(5, 2, new ItemTile("CATS"));
        bs30.setTile(0, 3, new ItemTile("PLANTS"));
        bs30.setTile(1, 3, new ItemTile("PLANTS"));
        bs30.setTile(2, 3, new ItemTile("CATS"));
        bs30.setTile(3, 3, new ItemTile("TROPHIES"));
        bs30.setTile(4, 3, new ItemTile("TROPHIES"));
        bs30.setTile(5, 3, new ItemTile("CATS"));
        bs30.setTile(0, 4, new ItemTile("BOOKS"));
        bs30.setTile(1, 4, new ItemTile("FRAMES"));
        bs30.setTile(2, 4, new ItemTile("TROPHIES"));
        bs30.setTile(3, 4, new ItemTile("GAMES"));
        bs30.setTile(4, 4, new ItemTile("TROPHIES"));
        bs30.setTile(5, 4, new ItemTile("BOOKS"));
        c44.checkGoal(bs30);
        assertEquals(1, c44.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_SECOND() {
        CommonGoalCard c45 = new CommonGoalCard3(new Launcher());
        c45.initNumCompleted();
        BookShelf bs31 = new BookShelf();
        bs31.setTile(0, 0, new ItemTile("BOOKS"));
        bs31.setTile(1, 0, new ItemTile("BOOKS"));
        bs31.setTile(2, 0, new ItemTile("BOOKS"));
        bs31.setTile(3, 0, new ItemTile("BOOKS"));
        bs31.setTile(4, 0, new ItemTile("GAMES"));
        bs31.setTile(5, 0, new ItemTile("CATS"));
        bs31.setTile(0, 1, new ItemTile("FRAMES"));
        bs31.setTile(1, 1, new ItemTile("GAMES"));
        bs31.setTile(2, 1, new ItemTile("FRAMES"));
        bs31.setTile(3, 1, new ItemTile("FRAMES"));
        bs31.setTile(4, 1, new ItemTile("GAMES"));
        bs31.setTile(5, 1, new ItemTile("CATS"));
        bs31.setTile(0, 2, new ItemTile("PLANTS"));
        bs31.setTile(1, 2, new ItemTile("PLANTS"));
        bs31.setTile(2, 2, new ItemTile("FRAMES"));
        bs31.setTile(3, 2, new ItemTile("CATS"));
        bs31.setTile(4, 2, new ItemTile("TROPHIES"));
        bs31.setTile(5, 2, new ItemTile("CATS"));
        bs31.setTile(0, 3, new ItemTile("PLANTS"));
        bs31.setTile(1, 3, new ItemTile("PLANTS"));
        bs31.setTile(2, 3, new ItemTile("FRAMES"));
        bs31.setTile(3, 3, new ItemTile("TROPHIES"));
        bs31.setTile(4, 3, new ItemTile("TROPHIES"));
        bs31.setTile(5, 3, new ItemTile("BOOKS"));
        bs31.setTile(0, 4, new ItemTile("BOOKS"));
        bs31.setTile(1, 4, new ItemTile("FRAMES"));
        bs31.setTile(2, 4, new ItemTile("TROPHIES"));
        bs31.setTile(3, 4, new ItemTile("GAMES"));
        bs31.setTile(4, 4, new ItemTile("TROPHIES"));
        bs31.setTile(5, 4, new ItemTile("BOOKS"));
        c45.checkGoal(bs31);
        assertEquals(1, c45.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_THIRD() {                 //MORE THAN FOUR GROUPS
        CommonGoalCard c46 = new CommonGoalCard3(new Launcher());
        c46.initNumCompleted();
        BookShelf bs32 = new BookShelf();
        bs32.setTile(0, 0, new ItemTile("BOOKS"));
        bs32.setTile(1, 0, new ItemTile("BOOKS"));
        bs32.setTile(2, 0, new ItemTile("BOOKS"));
        bs32.setTile(3, 0, new ItemTile("BOOKS"));
        bs32.setTile(4, 0, new ItemTile("GAMES"));
        bs32.setTile(5, 0, new ItemTile("CATS"));
        bs32.setTile(0, 1, new ItemTile("FRAMES"));
        bs32.setTile(1, 1, new ItemTile("GAMES"));
        bs32.setTile(2, 1, new ItemTile("FRAMES"));
        bs32.setTile(3, 1, new ItemTile("FRAMES"));
        bs32.setTile(4, 1, new ItemTile("GAMES"));
        bs32.setTile(5, 1, new ItemTile("CATS"));
        bs32.setTile(0, 2, new ItemTile("PLANTS"));
        bs32.setTile(1, 2, new ItemTile("PLANTS"));
        bs32.setTile(2, 2, new ItemTile("FRAMES"));
        bs32.setTile(3, 2, new ItemTile("CATS"));
        bs32.setTile(4, 2, new ItemTile("TROPHIES"));
        bs32.setTile(5, 2, new ItemTile("CATS"));
        bs32.setTile(0, 3, new ItemTile("PLANTS"));
        bs32.setTile(1, 3, new ItemTile("PLANTS"));
        bs32.setTile(2, 3, new ItemTile("FRAMES"));
        bs32.setTile(3, 3, new ItemTile("TROPHIES"));
        bs32.setTile(4, 3, new ItemTile("TROPHIES"));
        bs32.setTile(5, 3, new ItemTile("CATS"));
        bs32.setTile(0, 4, new ItemTile("BOOKS"));
        bs32.setTile(1, 4, new ItemTile("FRAMES"));
        bs32.setTile(2, 4, new ItemTile("TROPHIES"));
        bs32.setTile(3, 4, new ItemTile("GAMES"));
        bs32.setTile(4, 4, new ItemTile("TROPHIES"));
        bs32.setTile(5, 4, new ItemTile("BOOKS"));
        c46.checkGoal(bs32);
        assertEquals(1, c46.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_FOURTH() {
        CommonGoalCard c47 = new CommonGoalCard3(new Launcher());
        c47.initNumCompleted();
        BookShelf bs33 = new BookShelf();
        bs33.setTile(0, 0, new ItemTile("BOOKS"));
        bs33.setTile(1, 0, new ItemTile("BOOKS"));
        bs33.setTile(2, 0, new ItemTile("BOOKS"));
        bs33.setTile(3, 0, new ItemTile("BOOKS"));
        bs33.setTile(4, 0, new ItemTile("GAMES"));
        bs33.setTile(5, 0, new ItemTile("CATS"));
        bs33.setTile(0, 1, new ItemTile("FRAMES"));
        bs33.setTile(1, 1, new ItemTile("GAMES"));
        bs33.setTile(2, 1, new ItemTile("FRAMES"));
        bs33.setTile(3, 1, new ItemTile("FRAMES"));
        bs33.setTile(4, 1, new ItemTile("GAMES"));
        bs33.setTile(5, 1, new ItemTile("CATS"));
        bs33.setTile(0, 2, new ItemTile("PLANTS"));
        bs33.setTile(1, 2, new ItemTile("PLANTS"));
        bs33.setTile(2, 2, new ItemTile("FRAMES"));
        bs33.setTile(3, 2, new ItemTile("CATS"));
        bs33.setTile(4, 2, new ItemTile("TROPHIES"));
        bs33.setTile(5, 2, new ItemTile("CATS"));
        bs33.setTile(0, 3, new ItemTile("PLANTS"));
        bs33.setTile(1, 3, new ItemTile("PLANTS"));
        bs33.setTile(2, 3, new ItemTile("FRAMES"));
        bs33.setTile(3, 3, new ItemTile("TROPHIES"));
        bs33.setTile(4, 3, new ItemTile("TROPHIES"));
        bs33.setTile(5, 3, new ItemTile("BOOKS"));
        bs33.setTile(0, 4, new ItemTile("BOOKS"));
        bs33.setTile(1, 4, new ItemTile("FRAMES"));
        bs33.setTile(2, 4, new ItemTile("FRAMES"));
        bs33.setTile(3, 4, new ItemTile("GAMES"));
        bs33.setTile(4, 4, new ItemTile("TROPHIES"));
        bs33.setTile(5, 4, new ItemTile("BOOKS"));
        c47.checkGoal(bs33);
        assertEquals(0, c47.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_FIFTH() {
        CommonGoalCard c47 = new CommonGoalCard3(new Launcher());
        c47.initNumCompleted();
        BookShelf bs33 = new BookShelf();
        bs33.setTile(0, 0, new ItemTile("BOOKS"));
        bs33.setTile(1, 0, new ItemTile("FRAMES"));
        bs33.setTile(2, 0, new ItemTile("FRAMES"));
        bs33.setTile(3, 0, new ItemTile("FRAMES"));
        bs33.setTile(4, 0, new ItemTile("FRAMES"));
        bs33.setTile(5, 0, new ItemTile("CATS"));
        bs33.setTile(0, 1, new ItemTile("FRAMES"));
        bs33.setTile(1, 1, new ItemTile("GAMES"));
        bs33.setTile(2, 1, new ItemTile("TROPHIES"));
        bs33.setTile(3, 1, new ItemTile("TROPHIES"));
        bs33.setTile(4, 1, new ItemTile("GAMES"));
        bs33.setTile(5, 1, new ItemTile("CATS"));
        bs33.setTile(0, 2, new ItemTile("PLANTS"));
        bs33.setTile(1, 2, new ItemTile("PLANTS"));
        bs33.setTile(2, 2, new ItemTile("TROPHIES"));
        bs33.setTile(3, 2, new ItemTile("CATS"));
        bs33.setTile(4, 2, new ItemTile("TROPHIES"));
        bs33.setTile(5, 2, new ItemTile("CATS"));
        bs33.setTile(0, 3, new ItemTile("PLANTS"));
        bs33.setTile(1, 3, new ItemTile("PLANTS"));
        bs33.setTile(2, 3, new ItemTile("TROPHIES"));
        bs33.setTile(3, 3, new ItemTile("GAMES"));
        bs33.setTile(4, 3, new ItemTile("TROPHIES"));
        bs33.setTile(5, 3, new ItemTile("BOOKS"));
        bs33.setTile(0, 4, new ItemTile("FRAMES"));
        bs33.setTile(1, 4, new ItemTile("GAMES"));
        bs33.setTile(2, 4, new ItemTile("GAMES"));
        bs33.setTile(3, 4, new ItemTile("GAMES"));
        bs33.setTile(4, 4, new ItemTile("TROPHIES"));
        bs33.setTile(5, 4, new ItemTile("BOOKS"));
        c47.checkGoal(bs33);
        assertEquals(1, c47.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_SIXTH() {
        CommonGoalCard c47 = new CommonGoalCard3(new Launcher());
        c47.initNumCompleted();
        BookShelf bs33 = new BookShelf();
        bs33.setTile(0, 0, new ItemTile("FRAMES"));
        bs33.setTile(1, 0, new ItemTile("FRAMES"));
        bs33.setTile(2, 0, new ItemTile("FRAMES"));
        bs33.setTile(3, 0, new ItemTile("FRAMES"));
        bs33.setTile(4, 0, new ItemTile("TROPHIES"));
        bs33.setTile(5, 0, new ItemTile("FRAMES"));
        bs33.setTile(5, 1, new ItemTile("FRAMES"));
        bs33.setTile(5, 2, new ItemTile("FRAMES"));
        bs33.setTile(5, 3, new ItemTile("FRAMES"));
        bs33.setTile(1, 4, new ItemTile("FRAMES"));
        bs33.setTile(2, 4, new ItemTile("FRAMES"));
        bs33.setTile(3, 4, new ItemTile("FRAMES"));
        bs33.setTile(4, 4, new ItemTile("FRAMES"));
        bs33.setTile(0, 2, new ItemTile("FRAMES"));
        bs33.setTile(1, 2, new ItemTile("FRAMES"));
        bs33.setTile(2, 2, new ItemTile("FRAMES"));
        bs33.setTile(3, 2, new ItemTile("FRAMES"));
        c47.checkGoal(bs33);
        assertEquals(1, c47.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_SEVENTH() {
        CommonGoalCard c47 = new CommonGoalCard3(new Launcher());
        c47.initNumCompleted();
        BookShelf bs33 = new BookShelf();
        bs33.setTile(0, 0, new ItemTile("FRAMES"));
        bs33.setTile(1, 0, new ItemTile("FRAMES"));
        bs33.setTile(2, 0, new ItemTile("FRAMES"));
        bs33.setTile(3, 0, new ItemTile("FRAMES"));
        bs33.setTile(4, 0, new ItemTile("FRAMES"));
        bs33.setTile(5, 0, new ItemTile("FRAMES"));
        bs33.setTile(5, 1, new ItemTile("FRAMES"));
        bs33.setTile(5, 2, new ItemTile("FRAMES"));
        bs33.setTile(5, 3, new ItemTile("FRAMES"));
        bs33.setTile(1, 4, new ItemTile("FRAMES"));
        bs33.setTile(2, 4, new ItemTile("FRAMES"));
        bs33.setTile(3, 4, new ItemTile("FRAMES"));
        bs33.setTile(4, 4, new ItemTile("FRAMES"));
        bs33.setTile(0, 2, new ItemTile("FRAMES"));
        bs33.setTile(1, 2, new ItemTile("FRAMES"));
        bs33.setTile(2, 2, new ItemTile("FRAMES"));
        bs33.setTile(3, 2, new ItemTile("FRAMES"));
        c47.checkGoal(bs33);
        assertEquals(0, c47.getNumCompleted());
    }
    public void testCheckGoalCardCGC3_EIGHTH() {
        CommonGoalCard c47 = new CommonGoalCard3(new Launcher());
        c47.initNumCompleted();
        BookShelf bs33 = new BookShelf();
        bs33.setTile(0, 0, new ItemTile("FRAMES"));
        bs33.setTile(1, 0, new ItemTile("FRAMES"));
        bs33.setTile(2, 0, new ItemTile("FRAMES"));
        bs33.setTile(3, 0, new ItemTile("FRAMES"));
        bs33.setTile(4, 0, new ItemTile("TROPHIES"));
        bs33.setTile(5, 0, new ItemTile("CATS"));
        bs33.setTile(5, 1, new ItemTile("CATS"));
        bs33.setTile(5, 2, new ItemTile("CATS"));
        bs33.setTile(5, 3, new ItemTile("CATS"));
        bs33.setTile(1, 4, new ItemTile("GAMES"));
        bs33.setTile(2, 4, new ItemTile("GAMES"));
        bs33.setTile(3, 4, new ItemTile("GAMES"));
        bs33.setTile(4, 4, new ItemTile("GAMES"));
        bs33.setTile(0, 2, new ItemTile("BOOKS"));
        bs33.setTile(1, 2, new ItemTile("BOOKS"));
        bs33.setTile(2, 2, new ItemTile("BOOKS"));
        bs33.setTile(3, 2, new ItemTile("BOOKS"));
        c47.checkGoal(bs33);
        assertEquals(1, c47.getNumCompleted());
    }
}