package it.polimi.ingsw.model.board.goalCards;

import junit.framework.TestCase;
import it.polimi.ingsw.model.board.goalCards.CommonGoalCard;
import it.polimi.ingsw.model.board.goalCards.CommonGoalCard4;
import it.polimi.ingsw.Launcher;
import it.polimi.ingsw.model.board.ItemTile;
import it.polimi.ingsw.model.player.BookShelf;

public class CommonGoalCard4Test extends TestCase {

    public void testCheckGoalCardCGC4_FIRST(){          //LEFT SIDE SQUARES
        CommonGoalCard c33 = new CommonGoalCard4(new Launcher());
        c33.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("PLANTS"));
        bs26.setTile(0, 1, new ItemTile("PLANTS"));
        bs26.setTile(1, 0, new ItemTile("PLANTS"));
        bs26.setTile(1, 1, new ItemTile("PLANTS"));
        bs26.setTile(0, 2, new ItemTile("GAMES"));
        bs26.setTile(0, 3, new ItemTile("TROPHIES"));
        bs26.setTile(0, 4, new ItemTile("CATS"));
        bs26.setTile(1, 2, new ItemTile("TROPHIES"));
        bs26.setTile(1, 3, new ItemTile("FRAMES"));
        bs26.setTile(1, 4, new ItemTile("GAMES"));
        bs26.setTile(2, 0, new ItemTile("PLANTS"));
        bs26.setTile(2, 1, new ItemTile("CATS"));
        bs26.setTile(2, 2, new ItemTile("BOOKS"));
        bs26.setTile(2, 3, new ItemTile("FRAMES"));
        bs26.setTile(2, 4, new ItemTile("GAMES"));
        bs26.setTile(3, 0, new ItemTile("TROPHIES"));
        bs26.setTile(3, 1, new ItemTile("GAMES"));
        bs26.setTile(3, 2, new ItemTile("FRAMES"));
        bs26.setTile(3, 3, new ItemTile("BOOKS"));
        bs26.setTile(3, 4, new ItemTile("CATS"));
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("PLANTS"));
        bs26.setTile(5, 0, new ItemTile("PLANTS"));
        bs26.setTile(5, 1, new ItemTile("PLANTS"));
        bs26.setTile(4, 2, new ItemTile("CATS"));
        bs26.setTile(4, 3, new ItemTile("BOOKS"));
        bs26.setTile(4, 4, new ItemTile("FRAMES"));
        bs26.setTile(5, 2, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("TROPHIES"));
        bs26.setTile(5, 4, new ItemTile("GAMES"));
        c33.checkGoal(bs26);
        assertEquals(1, c33.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_SECOND(){             //RIGHT SIDE SQUARES
        CommonGoalCard c34 = new CommonGoalCard4(new Launcher());
        c34.initNumCompleted();
        BookShelf bs27 = new BookShelf();
        bs27.setTile(0, 0, new ItemTile("PLANTS"));
        bs27.setTile(0, 1, new ItemTile("CATS"));
        bs27.setTile(1, 0, new ItemTile("BOOKS"));
        bs27.setTile(1, 1, new ItemTile("PLANTS"));
        bs27.setTile(0, 2, new ItemTile("GAMES"));
        bs27.setTile(0, 3, new ItemTile("TROPHIES"));
        bs27.setTile(0, 4, new ItemTile("TROPHIES"));
        bs27.setTile(1, 2, new ItemTile("FRAMES"));
        bs27.setTile(1, 3, new ItemTile("TROPHIES"));
        bs27.setTile(1, 4, new ItemTile("TROPHIES"));
        bs27.setTile(2, 0, new ItemTile("PLANTS"));
        bs27.setTile(2, 1, new ItemTile("CATS"));
        bs27.setTile(2, 2, new ItemTile("BOOKS"));
        bs27.setTile(2, 3, new ItemTile("FRAMES"));
        bs27.setTile(2, 4, new ItemTile("GAMES"));
        bs27.setTile(3, 0, new ItemTile("TROPHIES"));
        bs27.setTile(3, 1, new ItemTile("GAMES"));
        bs27.setTile(3, 2, new ItemTile("FRAMES"));
        bs27.setTile(3, 3, new ItemTile("BOOKS"));
        bs27.setTile(3, 4, new ItemTile("CATS"));
        bs27.setTile(4, 0, new ItemTile("PLANTS"));
        bs27.setTile(4, 1, new ItemTile("CATS"));
        bs27.setTile(5, 0, new ItemTile("CATS"));
        bs27.setTile(5, 1, new ItemTile("PLANTS"));
        bs27.setTile(4, 2, new ItemTile("GAMES"));
        bs27.setTile(4, 3, new ItemTile("TROPHIES"));
        bs27.setTile(4, 4, new ItemTile("TROPHIES"));
        bs27.setTile(5, 2, new ItemTile("GAMES"));
        bs27.setTile(5, 3, new ItemTile("TROPHIES"));
        bs27.setTile(5, 4, new ItemTile("TROPHIES"));
        c34.checkGoal(bs27);
        assertEquals(1, c34.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_THIRD(){          //UPPER LEFT SQUARE AND LOWER RIGHT SQUARE
        CommonGoalCard c35 = new CommonGoalCard4(new Launcher());
        c35.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("CATS"));
        bs26.setTile(0, 1, new ItemTile("CATS"));
        bs26.setTile(1, 0, new ItemTile("CATS"));
        bs26.setTile(1, 1, new ItemTile("CATS"));
        bs26.setTile(0, 2, new ItemTile("GAMES"));
        bs26.setTile(0, 3, new ItemTile("TROPHIES"));
        bs26.setTile(0, 4, new ItemTile("CATS"));
        bs26.setTile(1, 2, new ItemTile("TROPHIES"));
        bs26.setTile(1, 3, new ItemTile("FRAMES"));
        bs26.setTile(1, 4, new ItemTile("GAMES"));
        bs26.setTile(2, 0, new ItemTile("PLANTS"));
        bs26.setTile(2, 1, new ItemTile("CATS"));
        bs26.setTile(2, 2, new ItemTile("BOOKS"));
        bs26.setTile(2, 3, new ItemTile("FRAMES"));
        bs26.setTile(2, 4, new ItemTile("GAMES"));
        bs26.setTile(3, 0, new ItemTile("TROPHIES"));
        bs26.setTile(3, 1, new ItemTile("GAMES"));
        bs26.setTile(3, 2, new ItemTile("FRAMES"));
        bs26.setTile(3, 3, new ItemTile("BOOKS"));
        bs26.setTile(3, 4, new ItemTile("CATS"));
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("GAMES"));
        bs26.setTile(5, 0, new ItemTile("FRAMES"));
        bs26.setTile(5, 1, new ItemTile("PLANTS"));
        bs26.setTile(4, 2, new ItemTile("FRAMES"));
        bs26.setTile(4, 3, new ItemTile("CATS"));
        bs26.setTile(4, 4, new ItemTile("CATS"));
        bs26.setTile(5, 2, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("CATS"));
        bs26.setTile(5, 4, new ItemTile("CATS"));
        c35.checkGoal(bs26);
        assertEquals(1, c35.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_FOURTH(){     //UPPER RIGHT SQUARE AND LOWER LEFT SQUARE
        CommonGoalCard c36 = new CommonGoalCard4(new Launcher());
        c36.initNumCompleted();
        BookShelf bs27 = new BookShelf();
        bs27.setTile(0, 0, new ItemTile("PLANTS"));
        bs27.setTile(0, 1, new ItemTile("CATS"));
        bs27.setTile(1, 0, new ItemTile("BOOKS"));
        bs27.setTile(1, 1, new ItemTile("PLANTS"));
        bs27.setTile(0, 2, new ItemTile("GAMES"));
        bs27.setTile(0, 3, new ItemTile("BOOKS"));
        bs27.setTile(0, 4, new ItemTile("BOOKS"));
        bs27.setTile(1, 2, new ItemTile("FRAMES"));
        bs27.setTile(1, 3, new ItemTile("BOOKS"));
        bs27.setTile(1, 4, new ItemTile("BOOKS"));
        bs27.setTile(2, 0, new ItemTile("PLANTS"));
        bs27.setTile(2, 1, new ItemTile("CATS"));
        bs27.setTile(2, 2, new ItemTile("BOOKS"));
        bs27.setTile(2, 3, new ItemTile("FRAMES"));
        bs27.setTile(2, 4, new ItemTile("GAMES"));
        bs27.setTile(3, 0, new ItemTile("TROPHIES"));
        bs27.setTile(3, 1, new ItemTile("GAMES"));
        bs27.setTile(3, 2, new ItemTile("FRAMES"));
        bs27.setTile(3, 3, new ItemTile("BOOKS"));
        bs27.setTile(3, 4, new ItemTile("CATS"));
        bs27.setTile(4, 0, new ItemTile("BOOKS"));
        bs27.setTile(4, 1, new ItemTile("BOOKS"));
        bs27.setTile(5, 0, new ItemTile("BOOKS"));
        bs27.setTile(5, 1, new ItemTile("BOOKS"));
        bs27.setTile(4, 2, new ItemTile("GAMES"));
        bs27.setTile(4, 3, new ItemTile("TROPHIES"));
        bs27.setTile(4, 4, new ItemTile("FRAMES"));
        bs27.setTile(5, 2, new ItemTile("GAMES"));
        bs27.setTile(5, 3, new ItemTile("TROPHIES"));
        bs27.setTile(5, 4, new ItemTile("CATS"));
        c36.checkGoal(bs27);
        assertEquals(1, c36.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_FIFTH(){              //TWO SQUARES IN THE MIDDLE LEFT SIDE AND MIDDLE RIGHT SIDE
        CommonGoalCard c37 = new CommonGoalCard4(new Launcher());
        c37.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("PLANTS"));
        bs26.setTile(0, 1, new ItemTile("CATS"));
        bs26.setTile(1, 0, new ItemTile("CATS"));
        bs26.setTile(1, 1, new ItemTile("PLANTS"));
        bs26.setTile(0, 2, new ItemTile("GAMES"));
        bs26.setTile(0, 3, new ItemTile("TROPHIES"));
        bs26.setTile(0, 4, new ItemTile("CATS"));
        bs26.setTile(1, 2, new ItemTile("TROPHIES"));
        bs26.setTile(1, 3, new ItemTile("FRAMES"));
        bs26.setTile(1, 4, new ItemTile("GAMES"));
        bs26.setTile(2, 0, new ItemTile("GAMES"));
        bs26.setTile(2, 1, new ItemTile("GAMES"));
        bs26.setTile(2, 2, new ItemTile("BOOKS"));
        bs26.setTile(2, 3, new ItemTile("GAMES"));
        bs26.setTile(2, 4, new ItemTile("GAMES"));
        bs26.setTile(3, 0, new ItemTile("GAMES"));
        bs26.setTile(3, 1, new ItemTile("GAMES"));
        bs26.setTile(3, 2, new ItemTile("BOOKS"));
        bs26.setTile(3, 3, new ItemTile("GAMES"));
        bs26.setTile(3, 4, new ItemTile("GAMES"));
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("TROPHIES"));
        bs26.setTile(5, 0, new ItemTile("FRAMES"));
        bs26.setTile(5, 1, new ItemTile("BOOKS"));
        bs26.setTile(4, 2, new ItemTile("BOOKS"));
        bs26.setTile(4, 3, new ItemTile("CATS"));
        bs26.setTile(4, 4, new ItemTile("FRAMES"));
        bs26.setTile(5, 2, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("TROPHIES"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c37.checkGoal(bs26);
        assertEquals(1, c37.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_SIXTH(){              //TWO GENERAL SQUARES
        CommonGoalCard c38 = new CommonGoalCard4(new Launcher());
        c38.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("PLANTS"));
        bs26.setTile(0, 1, new ItemTile("CATS"));
        bs26.setTile(1, 0, new ItemTile("CATS"));
        bs26.setTile(1, 1, new ItemTile("PLANTS"));
        bs26.setTile(0, 2, new ItemTile("FRAMES"));
        bs26.setTile(0, 3, new ItemTile("FRAMES"));
        bs26.setTile(0, 4, new ItemTile("BOOKS"));
        bs26.setTile(1, 2, new ItemTile("FRAMES"));
        bs26.setTile(1, 3, new ItemTile("FRAMES"));
        bs26.setTile(1, 4, new ItemTile("GAMES"));
        bs26.setTile(2, 0, new ItemTile("GAMES"));
        bs26.setTile(2, 1, new ItemTile("CATS"));
        bs26.setTile(2, 2, new ItemTile("BOOKS"));
        bs26.setTile(2, 3, new ItemTile("GAMES"));
        bs26.setTile(2, 4, new ItemTile("FRAMES"));
        bs26.setTile(3, 0, new ItemTile("PLANTS"));
        bs26.setTile(3, 1, new ItemTile("GAMES"));
        bs26.setTile(3, 2, new ItemTile("BOOKS"));
        bs26.setTile(3, 3, new ItemTile("FRAMES"));
        bs26.setTile(3, 4, new ItemTile("FRAMES"));
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("TROPHIES"));
        bs26.setTile(5, 0, new ItemTile("FRAMES"));
        bs26.setTile(5, 1, new ItemTile("BOOKS"));
        bs26.setTile(4, 2, new ItemTile("BOOKS"));
        bs26.setTile(4, 3, new ItemTile("FRAMES"));
        bs26.setTile(4, 4, new ItemTile("FRAMES"));
        bs26.setTile(5, 2, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("TROPHIES"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c38.checkGoal(bs26);
        assertEquals(1, c38.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_SEVENTH(){              //NO SQUARES
        CommonGoalCard c39 = new CommonGoalCard4(new Launcher());
        c39.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("PLANTS"));
        bs26.setTile(1, 0, new ItemTile("CATS"));
        bs26.setTile(2, 0, new ItemTile("FRAMES"));
        bs26.setTile(3, 0, new ItemTile("BOOKS"));
        bs26.setTile(4, 0, new ItemTile("GAMES"));
        bs26.setTile(5, 0, new ItemTile("TROPHIES"));
        bs26.setTile(0, 1, new ItemTile("TROPHIES"));
        bs26.setTile(1, 1, new ItemTile("GAMES"));
        bs26.setTile(2, 1, new ItemTile("BOOKS"));
        bs26.setTile(3, 1, new ItemTile("FRAMES"));
        bs26.setTile(4, 1, new ItemTile("PLANTS"));
        bs26.setTile(5, 1, new ItemTile("CATS"));
        bs26.setTile(0, 2, new ItemTile("PLANTS"));
        bs26.setTile(1, 2, new ItemTile("GAMES"));
        bs26.setTile(2, 2, new ItemTile("FRAMES"));
        bs26.setTile(3, 2, new ItemTile("CATS"));
        bs26.setTile(4, 2, new ItemTile("TROPHIES"));
        bs26.setTile(5, 2, new ItemTile("BOOKS"));
        bs26.setTile(0, 3, new ItemTile("BOOKS"));
        bs26.setTile(1, 3, new ItemTile("TROPHIES"));
        bs26.setTile(2, 3, new ItemTile("CATS"));
        bs26.setTile(3, 3, new ItemTile("FRAMES"));
        bs26.setTile(4, 3, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("PLANTS"));
        bs26.setTile(0, 4, new ItemTile("BOOKS"));
        bs26.setTile(1, 4, new ItemTile("FRAMES"));
        bs26.setTile(2, 4, new ItemTile("TROPHIES"));
        bs26.setTile(3, 4, new ItemTile("GAMES"));
        bs26.setTile(4, 4, new ItemTile("CATS"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c39.checkGoal(bs26);
        assertEquals(0, c39.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_EIGHTH(){              //RECTANGLE 3 x 2, IT IS NOT CONSIDERED AS TWO SEPARATED
                                                                //SQUARES 2 X 2
        CommonGoalCard c40 = new CommonGoalCard4(new Launcher());
        c40.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("PLANTS"));
        bs26.setTile(1, 0, new ItemTile("PLANTS"));
        bs26.setTile(2, 0, new ItemTile("FRAMES"));
        bs26.setTile(3, 0, new ItemTile("BOOKS"));
        bs26.setTile(4, 0, new ItemTile("GAMES"));
        bs26.setTile(5, 0, new ItemTile("TROPHIES"));
        bs26.setTile(0, 1, new ItemTile("PLANTS"));
        bs26.setTile(1, 1, new ItemTile("PLANTS"));
        bs26.setTile(2, 1, new ItemTile("BOOKS"));
        bs26.setTile(3, 1, new ItemTile("FRAMES"));
        bs26.setTile(4, 1, new ItemTile("GAMES"));
        bs26.setTile(5, 1, new ItemTile("CATS"));
        bs26.setTile(0, 2, new ItemTile("PLANTS"));
        bs26.setTile(1, 2, new ItemTile("PLANTS"));
        bs26.setTile(2, 2, new ItemTile("FRAMES"));
        bs26.setTile(3, 2, new ItemTile("CATS"));
        bs26.setTile(4, 2, new ItemTile("TROPHIES"));
        bs26.setTile(5, 2, new ItemTile("BOOKS"));
        bs26.setTile(0, 3, new ItemTile("BOOKS"));
        bs26.setTile(1, 3, new ItemTile("TROPHIES"));
        bs26.setTile(2, 3, new ItemTile("CATS"));
        bs26.setTile(3, 3, new ItemTile("FRAMES"));
        bs26.setTile(4, 3, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("PLANTS"));
        bs26.setTile(0, 4, new ItemTile("BOOKS"));
        bs26.setTile(1, 4, new ItemTile("FRAMES"));
        bs26.setTile(2, 4, new ItemTile("TROPHIES"));
        bs26.setTile(3, 4, new ItemTile("GAMES"));
        bs26.setTile(4, 4, new ItemTile("CATS"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c40.checkGoal(bs26);
        assertEquals(0, c40.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_NINTH(){          //MORE THAN TWO SQUARES CASE, EXACTLY FOUR SQUARES (UPPER LEFT,
                                                                //UPPER RIGHT, LOWER LEFT, LOWER RIGHT
        CommonGoalCard c44 = new CommonGoalCard4(new Launcher());
        c44.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(0, 0, new ItemTile("PLANTS"));
        bs26.setTile(0, 1, new ItemTile("PLANTS"));
        bs26.setTile(1, 0, new ItemTile("PLANTS"));
        bs26.setTile(1, 1, new ItemTile("PLANTS"));
        bs26.setTile(0, 2, new ItemTile("GAMES"));
        bs26.setTile(0, 3, new ItemTile("PLANTS"));
        bs26.setTile(0, 4, new ItemTile("PLANTS"));
        bs26.setTile(1, 2, new ItemTile("TROPHIES"));
        bs26.setTile(1, 3, new ItemTile("PLANTS"));
        bs26.setTile(1, 4, new ItemTile("PLANTS"));
        bs26.setTile(2, 0, new ItemTile("PLANTS"));
        bs26.setTile(2, 1, new ItemTile("CATS"));
        bs26.setTile(2, 2, new ItemTile("BOOKS"));
        bs26.setTile(2, 3, new ItemTile("FRAMES"));
        bs26.setTile(2, 4, new ItemTile("GAMES"));
        bs26.setTile(3, 0, new ItemTile("TROPHIES"));
        bs26.setTile(3, 1, new ItemTile("GAMES"));
        bs26.setTile(3, 2, new ItemTile("FRAMES"));
        bs26.setTile(3, 3, new ItemTile("BOOKS"));
        bs26.setTile(3, 4, new ItemTile("CATS"));
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("PLANTS"));
        bs26.setTile(5, 0, new ItemTile("PLANTS"));
        bs26.setTile(5, 1, new ItemTile("PLANTS"));
        bs26.setTile(4, 2, new ItemTile("CATS"));
        bs26.setTile(4, 3, new ItemTile("PLANTS"));
        bs26.setTile(4, 4, new ItemTile("PLANTS"));
        bs26.setTile(5, 2, new ItemTile("GAMES"));
        bs26.setTile(5, 3, new ItemTile("PLANTS"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c44.checkGoal(bs26);
        assertEquals(1, c44.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_TENTH() {
        CommonGoalCard c44 = new CommonGoalCard4(new Launcher());
        c44.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("PLANTS"));
        bs26.setTile(5, 0, new ItemTile("PLANTS"));
        bs26.setTile(5, 1, new ItemTile("PLANTS"));
        bs26.setTile(4, 3, new ItemTile("PLANTS"));
        bs26.setTile(4, 4, new ItemTile("PLANTS"));
        bs26.setTile(5, 3, new ItemTile("PLANTS"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c44.checkGoal(bs26);
        assertEquals(1, c44.getNumCompleted());
    }
    public void testCheckGoalCardCGC4_ELEVENTH() {
        CommonGoalCard c44 = new CommonGoalCard4(new Launcher());
        c44.initNumCompleted();
        BookShelf bs26 = new BookShelf();
        bs26.setTile(4, 0, new ItemTile("PLANTS"));
        bs26.setTile(4, 1, new ItemTile("PLANTS"));
        bs26.setTile(5, 0, new ItemTile("PLANTS"));
        bs26.setTile(5, 1, new ItemTile("PLANTS"));
        bs26.setTile(4, 3, new ItemTile("PLANTS"));
        bs26.setTile(4, 4, new ItemTile("CATS"));
        bs26.setTile(5, 3, new ItemTile("CATS"));
        bs26.setTile(5, 4, new ItemTile("PLANTS"));
        c44.checkGoal(bs26);
        assertEquals(0, c44.getNumCompleted());
    }
}
